# read the file
# start and end locations via 'docs/doc1994.pdf'
cpsvrs1994_orig <- readr::read_fwf(here::here('data', 'data1994.txt'),
                                   readr::fwf_cols(CPS_YEAR = c(67, 68),
                                                   CPS_STATE = c(93, 94),
                                                   CPS_AGE = c(122, 123),
                                                   CPS_SEX = c(129, 130),
                                                   CPS_EDU = c(137, 138),
                                                   CPS_RACE = c(139, 140),
                                                   CPS_HISP = c(157,158),
                                                   WEIGHT = c(613, 622),
                                                   VRS_VOTE = c(817, 818),
                                                   VRS_VOTEREG = c(819, 820),
                                                   VRS_VOTETIME = c(821, 822),
                                                   VRS_RESIDENCE = c(823, 824))) %>%
  mutate(CPS_YEAR = CPS_YEAR + 1900)

# set the factors
cpsvrs1994_factored <- cpsvrs1994_orig %>%
  mutate(CPS_STATE = factor(stringr::str_pad(CPS_STATE, width = 2, side = "left", pad = "0"),
                            levels = fips$state_code, labels = fips$state),
         CPS_AGE = ifelse(CPS_AGE < 0, NA, CPS_AGE),
         CPS_SEX = factor(CPS_SEX, levels = 1:2, labels = c("MALE", "FEMALE")),
         CPS_EDU = factor(CPS_EDU, levels = 31:46,
                          labels = c("LESS THAN 1ST GRADE",
                                     "1ST, 2ND, 3RD OR 4TH GRADE",
                                     "5TH OR 6TH GRADE",
                                     "7TH OR 8TH GRADE",
                                     "9TH GRADE",
                                     "10TH GRADE",
                                     "11TH GRADE",
                                     "12TH GRADE NO DIPLOMA",
                                     "HIGH SCHOOL GRAD-DIPLOMA OR EQUIV (GED)",
                                     "SOME COLLEGE BUT NO DEGREE",
                                     "ASSOCIATE DEGREE-OCCUPATIONAL/VOCATIONAL",
                                     "ASSOCIATE DEGREE-ACADEMIC PROGRAM",
                                     "BACHELOR'S DEGREE (EX: BA, AB, BS)",
                                     "MASTER'S DEGREE (EX: MA, MS, MEng, MEd, MSW)",
                                     "PROFESSIONAL SCHOOL DEG (EX: MD, DDS, DVM)",
                                     "DOCTORATE DEGREE (EX: PhD, EdD)"),
                          ordered = TRUE),
         CPS_RACE = factor(CPS_RACE, levels = 1:4,
                           labels = c("White",
                                      "Black",
                                      "American Indian, Aleut, Eskimo",
                                      "Asian or Pacific Islander")),
         CPS_HISP = factor(CPS_HISP, levels = 1:2,
                           labels = c("HISPANIC",
                                      "NON-HISPANIC")),
         VRS_VOTE = factor(VRS_VOTE, levels = c(1,2,-1,-2,-3,-9),
                           labels = c("Yes",
                                      "No",
                                      "Not in Universe",
                                      "Don't know",
                                      "Refused",
                                      "No Response")),
         VRS_VOTEREG = factor(VRS_VOTEREG, levels = c(1, 2, -1, -2, -3, -9),
                              labels = c("Yes",
                                         "No",
                                         "Not in Universe",
                                         "Don't know",
                                         "Refused",
                                         "No Response")),
         VRS_VOTETIME = factor(VRS_VOTETIME, levels = c(1:5, -1, -2, -3, -9),
                               labels = c("Before noon",
                                          "Noon to 4 p.m.",
                                          "4 p.m. to 6 p.m.",
                                          "After 6 p.m.",
                                          "Voted absentee",
                                          "Not in Universe",
                                          "Don't know",
                                          "Refused",
                                          "No Response")),
         VRS_RESIDENCE = factor(VRS_RESIDENCE, levels = c(1:6, -1, -2, -3, -9),
                                labels = c("Less than 1 month",
                                           "1-6 months",
                                           "7-11 months",
                                           "1-2 years",
                                           "3-4 years",
                                           "5 years or longer",
                                           "Not in Universe",
                                           "Don't know",
                                           "Refused",
                                           "No Response"),
                                ordered = TRUE)
  )
