# read the file
# start and end locations via 'docs/doc2000.pdf'
cpsvrs2000_orig <- readr::read_fwf(here::here('data', 'data2000.txt'),
                                   readr::fwf_cols(CPS_YEAR = c(18, 21),
                                                   CPS_STATE = c(93, 94),
                                                   CPS_AGE = c(122, 123),
                                                   CPS_SEX = c(129, 130),
                                                   CPS_EDU = c(137, 138),
                                                   CPS_RACE = c(139, 140),
                                                   CPS_HISP = c(155,156),
                                                   WEIGHT = c(605, 614),
                                                   VRS_VOTE = c(840, 841),
                                                   VRS_VOTEREG = c(842, 843),
                                                   VRS_NOVOTEWHY = c(844, 845),
                                                   VRS_VOTEMETHOD = c(846, 847),
                                                   VRS_REGSINCE95 = c(848, 849),
                                                   VRS_REGDMV = c(850, 851),
                                                   VRS_REGHOW = c(852, 853),
                                                   VRS_RESIDENCE = c(854, 855)))


# set the factors
cpsvrs2000_factored <- cpsvrs2000_orig %>%
  mutate(CPS_STATE = factor(stringr::str_pad(CPS_STATE, width = 2, side = "left", pad = "0"),
                            levels = fips$state_code, labels = fips$state),
         CPS_AGE = ifelse(CPS_AGE < 0, NA, CPS_AGE),
         CPS_SEX = factor(CPS_SEX, levels = 1:2, labels = c("MALE", "FEMALE")),
         CPS_EDU = factor(CPS_EDU, levels = 31:46,
                          labels = c("LESS THAN 1ST GRADE",
                                     "1ST, 2ND, 3RD OR 4TH GRADE",
                                     "5TH OR 6TH GRADE",
                                     "7TH OR 8TH GRADE",
                                     "9TH GRADE",
                                     "10TH GRADE",
                                     "11TH GRADE",
                                     "12TH GRADE NO DIPLOMA",
                                     "HIGH SCHOOL GRAD-DIPLOMA OR EQUIV (GED)",
                                     "SOME COLLEGE BUT NO DEGREE",
                                     "ASSOCIATE DEGREE-OCCUPATIONAL/VOCATIONAL",
                                     "ASSOCIATE DEGREE-ACADEMIC PROGRAM",
                                     "BACHELOR'S DEGREE (EX: BA, AB, BS)",
                                     "MASTER'S DEGREE (EX: MA, MS, MEng, MEd, MSW)",
                                     "PROFESSIONAL SCHOOL DEG (EX: MD, DDS, DVM)",
                                     "DOCTORATE DEGREE (EX: PhD, EdD)"),
                          ordered = TRUE),
         CPS_RACE = factor(CPS_RACE, levels = 1:4,
                           labels = c("White",
                                      "Black",
                                      "American Indian, Aleut, Eskimo",
                                      "Asian or Pacific Islander")),
         CPS_HISP = factor(CPS_HISP, levels = 1:2,
                           labels = c("HISPANIC",
                                      "NON-HISPANIC")),
         VRS_VOTE = factor(VRS_VOTE, levels = c(1,2,-1,-2,-3,-9),
                           labels = c("Yes",
                                      "No",
                                      "Not in Universe",
                                      "Don't know",
                                      "Refused",
                                      "No Response")),
         VRS_VOTEREG = factor(VRS_VOTEREG, levels = c(1, 2, -1, -2, -3, -9),
                              labels = c("Yes",
                                         "No",
                                         "Not in Universe",
                                         "Don't know",
                                         "Refused",
                                         "No Response")),
         VRS_NOVOTEWHY = factor(VRS_NOVOTEWHY, levels = c(1:11, -1, -2, -3, -9),
                                labels = c("Illness or disability (own or family's)",
                                           "Out of town or away from home",
                                           "Forgot to vote (or send in absentee ballot)",
                                           "Not interested, felt my vote wouldn't make a difference",
                                           "Too busy, conflicting work or school schedule",
                                           "Transportation problems",
                                           "Didn't like candidates or campaign issues",
                                           "Registration problems (i.e. didn't receive absentee ballot, not registered in current location)",
                                           "Bad weather conditions",
                                           "Inconvenient hours, polling place or hours or lines too long",
                                           "Other",
                                           "Not in Universe",
                                           "Don't know",
                                           "Refused",
                                           "No Response")),
         VRS_VOTEMETHOD = factor(VRS_VOTEMETHOD, levels = c(1:3, -1, -2, -3, -9),
                          labels = c("In person on election day",
                                     "In person before election day",
                                     "Voted by mail (absentee)",
                                     "Not in Universe",
                                     "Don't know",
                                     "Refused",
                                     "No Response")),
         VRS_REGSINCE95 = factor(VRS_REGSINCE95, levels = c(1:2, -1, -2, -3, -9),
                                 labels = c("Yes",
                                            "No",
                                            "Not in Universe",
                                            "Don't know",
                                            "Refused",
                                            "No Response")),
         VRS_REGDMV = factor(VRS_REGDMV, levels = c(1, 2, -1, -2, -3, -9),
                              labels = c("When driver's license was obtained/renewed",
                                         "Some other way",
                                         "Not in Universe",
                                         "Don't know",
                                         "Refused",
                                         "No Response")),
         # this is only asked of the people who said "some other way" to the DMV reg question
         VRS_REGHOW = factor(VRS_REGHOW, levels = c(1:7, -1, -2, -3, -9),
                             labels = c("At a public assistance agency (for example, a Medicaid, AFDC, or Food Stamps office, an office serving disabled persons, or an unemployment office)",
                                        "Registered by mail",
                                        "At a school, hospital, or on campus",
                                        "Went to a town hall or county/government registration office",
                                        "Filled out form at a registration drive (library, post office, or someone came to your door)",
                                        "Registered at polling place (on election or primary day)",
                                        "Other",
                                        "Not in Universe",
                                        "Don't know",
                                        "Refused",
                                        "No Response")),
         VRS_RESIDENCE = factor(VRS_RESIDENCE, levels = c(1:6, -1, -2, -3, -9),
                                labels = c("Less than 1 month",
                                           "1-6 months",
                                           "7-11 months",
                                           "1-2 years",
                                           "3-4 years",
                                           "5 years or longer",
                                           "Not in Universe",
                                           "Don't know",
                                           "Refused",
                                           "No Response"),
                                ordered = TRUE)
  )
