# read the file
# start and end locations via 'docs/doc1988.pdf'
cpsvrs1988_orig <- readr::read_fwf(here::here('data', 'data1988.txt'),
                                   readr::fwf_cols(CPS_YEAR = c(120, 120),
                                                   CPS_STATE = c(17, 18),
                                                   CPS_AGE = c(97, 98),
                                                   CPS_SEX = c(101, 101),
                                                   CPS_EDU = c(103, 104),
                                                   CPS_EDU_COMPLETE = c(105,105),
                                                   CPS_RACE = c(100, 100),
                                                   CPS_HISP = c(155, 155),
                                                   WEIGHT = c(121, 132),
                                                   VRS_VOTE = c(483, 483),
                                                   VRS_VOTEREG = c(484, 484),
                                                   VRS_REGPREV = c(485, 485),
                                                   VRS_FIRSTREG = c(486, 486)),
                                   na = c("", "NA", "-", "A")) %>%
  mutate(CPS_YEAR = CPS_YEAR + 1980) %>%
  mutate_at(vars(starts_with("VRS_")), ~replace(., is.na(.), -1))

# set the factors
cpsvrs1988_factored <- cpsvrs1988_orig %>%
  mutate(CPS_STATE = factor(CPS_STATE,
                            levels = c(11:16,
                                       21:23,
                                       31:35,
                                       41:47,
                                       51:59,
                                       61:64,
                                       71:74,
                                       81:88,
                                       91:95),
                            labels = c("Maine", "New Hampshire", "Vermont", "Massachusetts", "Rhode Island", "Connecticut",
                                       "New York", "New Jersey", "Pennsylvania",
                                       "Ohio", "Indiana", "Illinois", "Michigan", "Wisconsin",
                                       "Minnesota", "Iowa", "Missouri", "North Dakota", "South Dakota", "Nebraska", "Kansas",
                                       "Delaware", "Maryland", "District of Columbia", "Virgina", "West Virgina", "North Carolina", "South Carolina", "Georgia", "Florida",
                                       "Kentucky", "Tennessee", "Alabama", "Mississippi",
                                       "Arkansas", "Louisisana", "Oklahoma", "Texas",
                                       "Montana", "Idaho", "Wyoming", "Colorado", "New Mexico", "Arizona", "Utah", "Nevada",
                                       "Washington", "Oregon", "California", "Alaska", "Hawaii")),
         CPS_AGE = ifelse(CPS_AGE < 0, NA, CPS_AGE),
         CPS_SEX = factor(CPS_SEX, levels = 1:2, labels = c("MALE", "FEMALE")),
         CPS_EDU = factor(CPS_EDU, levels = 1:19,
                          labels = c("None",
                                     paste0("E", 1:8),
                                     paste0("H", 1:4),
                                     paste0("C", 1:5),
                                     "C6+"),
                          ordered = TRUE),
         CPS_EDU_COMPLETE = factor(CPS_EDU_COMPLETE,
                                   levels = 1:2,
                                   labels = c("Yes",
                                              "No")),
         CPS_RACE = factor(CPS_RACE, levels = 1:3,
                           labels = c("White",
                                      "Black",
                                      "Other")),
         CPS_HISP = factor(CPS_HISP, levels = 1:9,
                           labels = c("Mexican American",
                                      "Chicano",
                                      "Mexican",
                                      "Puerto Rican",
                                      "Cuban",
                                      "Central or South American",
                                      "Other Spanish",
                                      "All other",
                                      "Don't know")),
         VRS_VOTE = factor(VRS_VOTE, levels = c(1,2,3,8,9),
                           labels = c("Yes",
                                      "No",
                                      "Don't know",
                                      "No Response",
                                      "Not in Universe")),
         VRS_VOTEREG = factor(VRS_VOTEREG, levels = c(1,2,3,8,9),
                              labels = c("Yes",
                                         "No",
                                         "Don't know",
                                         "No Response",
                                         "Not in Universe")),
         VRS_REGPREV = factor(VRS_REGPREV, levels = c(1,2,3,8,9),
                               labels = c("Registered for this election",
                                          "Already registered",
                                          "Don't know",
                                          "No Response",
                                          "Not in Universe")),
         VRS_FIRSTREG = factor(VRS_FIRSTREG, levels = c(1,2,3,8,9),
                               labels = c("Yes",
                                          "No",
                                          "Don't know",
                                          "No Response",
                                          "Not in Universe"))
  )
