# read the file
# start and end locations via 'docs/doc2018.pdf'
cpsvrs2018_orig <- readr::read_fwf(here::here('data', 'data2018.txt'),
                                     readr::fwf_cols(CPS_YEAR = c(18, 21),
                                                     CPS_STATE = c(93, 94),
                                                     CPS_AGE = c(122, 123),
                                                     CPS_SEX = c(129, 130),
                                                     CPS_EDU = c(137,138),
                                                     CPS_RACE = c(139, 140),
                                                     CPS_HISP = c(157,158),
                                                     WEIGHT = c(613, 622),
                                                     VRS_VOTE = c(1001, 1002),
                                                     VRS_VOTEREG = c(1003, 1004),
                                                     VRS_NOREGWHY = c(1005, 1006),
                                                     VRS_NOVOTEWHY = c(1007, 1008),
                                                     VRS_VBM = c(1009, 1010),
                                                     VRS_ELEXDAY = c(1011, 1012),
                                                     VRS_REGHOW = c(1013, 1014),
                                                     VRS_RESIDENCE = c(1015, 1016)))


# set the factors
cpsvrs2018_factored <- cpsvrs2018_orig %>%
  mutate(CPS_STATE = factor(CPS_STATE, levels = fips$state_code, labels = fips$state),
         CPS_AGE = ifelse(CPS_AGE < 0, NA, CPS_AGE),
         CPS_SEX = factor(CPS_SEX, levels = 1:2, labels = c("MALE", "FEMALE")),
         CPS_EDU = factor(CPS_EDU, levels = 31:46,
                          labels = c("LESS THAN 1ST GRADE",
                                     "1ST, 2ND, 3RD OR 4TH GRADE",
                                     "5TH OR 6TH GRADE",
                                     "7TH OR 8TH GRADE",
                                     "9TH GRADE",
                                     "10TH GRADE",
                                     "11TH GRADE",
                                     "12TH GRADE NO DIPLOMA",
                                     "HIGH SCHOOL GRAD-DIPLOMA OR EQUIV (GED)",
                                     "SOME COLLEGE BUT NO DEGREE",
                                     "ASSOCIATE DEGREE-OCCUPATIONAL/VOCATIONAL",
                                     "ASSOCIATE DEGREE-ACADEMIC PROGRAM",
                                     "BACHELOR'S DEGREE (EX: BA, AB, BS)",
                                     "MASTER'S DEGREE (EX: MA, MS, MEng, MEd, MSW)",
                                     "PROFESSIONAL SCHOOL DEG (EX: MD, DDS, DVM)",
                                     "DOCTORATE DEGREE (EX: PhD, EdD)"),
                          ordered = TRUE),
         CPS_RACE = factor(CPS_RACE, levels = 1:26,
                           labels = c("White Only",
                                      "Black Only",
                                      "American Indian, Alaskan Native Only",
                                      "Asian Only",
                                      "Hawaiian/Pacific Islander Only",
                                      "White-Black",
                                      "White-AI",
                                      "White-Asian",
                                      "White-Hawaiian",
                                      "Black-AI",
                                      "Black-Asian",
                                      "Black-HP",
                                      "AI-Asian",
                                      "AI-HP",
                                      "Asian-HP",
                                      "W-B-AI",
                                      "W-B-A",
                                      "W-B-HP",
                                      "W-AI-A",
                                      "W-AI-HP",
                                      "W-A-HP",
                                      "B-AI-A",
                                      "W-B-AI-A",
                                      "W-AI-A-HP",
                                      "Other 3 Race Combinations",
                                      "Other 4 and 5 Race Combinations")),
         CPS_HISP = factor(CPS_HISP, levels = 1:2,
                           labels = c("HISPANIC",
                                      "NON-HISPANIC")),
         VRS_VOTE = factor(VRS_VOTE, levels = c(1,2,-1,-2,-3,-9),
                           labels = c("Yes",
                                      "No",
                                      "Not in Universe",
                                      "Don't know",
                                      "Refused",
                                      "No Response")),
         VRS_VOTEREG = factor(VRS_VOTEREG, levels = c(1, 2, -1, -2, -3, -9),
                              labels = c("Yes",
                                         "No",
                                         "Not in Universe",
                                         "Don't know",
                                         "Refused",
                                         "No Response")),
         VRS_NOREGWHY = factor(VRS_NOREGWHY, levels = c(1:9, -1, -2, -3, -9),
                               labels = c("Did not meet registration deadlines",
                                          "Did not know where or how to register",
                                          "Did not meet residency requirements/did not live here long enough",
                                          "Permanent illness or disability",
                                          "Difficulty with English",
                                          "Not interested in the election or not involved in politics",
                                          "My vote would not make a difference",
                                          "Not eligible to vote",
                                          "Other reason",
                                          "Not in Universe",
                                          "Don't know",
                                          "Refused",
                                          "No Response")),
         VRS_NOVOTEWHY = factor(VRS_NOVOTEWHY, levels = c(1:11, -1, -2, -3, -9),
                                labels = c("Illness or disability (own or family's)",
                                           "Out of town or away from home",
                                           "Forgot to vote (or send in absentee ballot)",
                                           "Not interested, felt my vote wouldn't make a difference",
                                           "Too busy, conflicting work or school schedule",
                                           "Transportation problems",
                                           "Didn't like candidates or campaign issues",
                                           "Registration problems (i.e. didn't receive absentee ballot, not registered in current location)",
                                           "Bad weather conditions",
                                           "Inconvenient hours, polling place or hours or lines too long",
                                           "Other",
                                           "Not in Universe",
                                           "Don't know",
                                           "Refused",
                                           "No Response")),
         VRS_VBM = factor(VRS_VBM, levels = c(1, 2, -1, -2, -3, -9),
                          labels = c("In person",
                                     "By mail",
                                     "Not in Universe",
                                     "Don't know",
                                     "Refused",
                                     "No Response")),
         VRS_ELEXDAY = factor(VRS_ELEXDAY, levels = c(1, 2, -1, -2, -3, -9),
                              labels = c("On election day",
                                         "Before election day",
                                         "Not in Universe",
                                         "Don't know",
                                         "Refused",
                                         "No Response")),
         VRS_REGHOW = factor(VRS_REGHOW, levels = c(1:9, -1, -2, -3, -9),
                             labels = c("At a department of motor vehicles (for example, when obtaining a driver's license or other identification card)",
                                        "At a public assistance agency (for example, a Medicaid, AFDC, or Food Stamps office, an office serving disabled persons, or an unemployment office)",
                                        "Registered by mail",
                                        "Registered using the internet or online",
                                        "At a school, hospital, or on campus",
                                        "Went to a town hall or county/government registration office",
                                        "Filled out form at a registration drive (library, post office, or someone came to your door)",
                                        "Registered at polling place (on election or primary day)",
                                        "Other",
                                        "Not in Universe",
                                        "Don't know",
                                        "Refused",
                                        "No Response")),
         VRS_RESIDENCE = factor(VRS_RESIDENCE, levels = c(1:4, -1, -2, -3, -9),
                                labels = c("Less than 1 year",
                                           "1-2 years",
                                           "3-4 years",
                                           "5 years or longer",
                                           "Not in Universe",
                                           "Don't know",
                                           "Refused",
                                           "No Response"),
                                ordered = TRUE)
  )
